import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Picallens - A learing platform.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo192.svg" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <meta name="description" content="Picallens a learning platform." />
        <link rel="apple-touch-icon" href="/logo192.svg" />
      </Head>

      <main>
      </main>
    </div>
  )
}
